version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgress
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_prod

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - ./logs:/var/log/myapp
    env_file:
      - .env
    networks:
      - app_prod

volumes:
  postgres_data:

networks:
  app_prod:
    driver: bridge
