version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_dev

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - '4001:8080'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_dev

volumes:
  postgres_data:

networks:
  app_dev:
    driver: bridge
