FROM node:22-alpine

RUN apk add --no-cache python3 py3-pip build-base

WORKDIR /app

RUN npm install -g @nestjs/cli

COPY package*.json ./
RUN npm install --legacy-peer-deps

RUN npm install prisma @prisma/client --legacy-peer-deps

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
