version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - app_dev

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_dev

volumes:
  postgres_data:
  postgres_logs:

networks:
  app_dev:
    driver: bridge
