FROM node:22-alpine

RUN apk add --no-cache python3 py3-pip build-base

WORKDIR /app

RUN npm install -g @nestjs/cli

COPY package*.json ./
RUN npm install --production

RUN npm install prisma @prisma/client

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
