-- AlterTable
ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT TO_CHAR(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
ALTER COLUMN "created_at" SET DATA TYPE TEXT,
ALTER COLUMN "updated_at" SET DEFAULT TO_CHAR(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
ALTER COLUMN "updated_at" SET DATA TYPE TEXT;
